* added test for existing vufind-folder * renamed image-tags * removed vanilla vufind from image

diff --git a/assets/entrypoint-php b/assets/entrypoint-php
--- a/assets/entrypoint-php
+++ b/assets/entrypoint-php
@@ -1,8 +1,10 @@
 #!/bin/sh
 set -e
 
-cp ${VUFIND_APPLICATION_PATH}/module/VuFind/sql/mysql.sql /init-db/mysql/
-cp ${VUFIND_APPLICATION_PATH}/module/VuFind/sql/pgsql.sql /init-db/psql/
+if [ ! -d "${VUFIND_APPLICATION_PATH}" ];then
+	echo "the application folder \"${VUFIND_APPLICATION_PATH}\" was not found. make shure to attach a sufficiently set up vufind container"
+	exit 1;
+fi;
 
 chown www-data:www-data ${VUFIND_APPLICATION_PATH} ${VUFIND_CACHE_DIR} -R
 
